### ISSUE TITLE
Not able to create any blog post

### ISSUE THREAD

**Issue by gabegaz** [Akash1362000/Django_BlogApp#6]
Thank you for this project. I can register and sign in. Can see my profile (although not similar to what I see on the gif image). I can also see my information in the database. But I am not able to create blog post. I was expecting something like "Create" in the page after I signed in.

**Comment by zablon-oigo** [comment]
> Thank you for this project. I can register and sign in. Can see my profile (although not similar to what I see on the gif image). I can also see my information in the database. But I am not able to create blog post. I was expecting something like "Create" in the page after I signed in.

@Akash1362000  Nice Project, I can solve this particular issue, If it has not yet been solved please assign it to me ....Thank you

**Comment by Akash1362000** [comment]
Sure @zablon-oigo, you can work on this issue and raise a PR for it.
